In [1]:
print("AI Lab 27-07-23")

AI Lab 27-07-23


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [4]:
ass=np.array([[1,2,3],[4,5,6]])
print(ass)

[[1 2 3]
 [4 5 6]]


In [6]:
print(ass.ndim) #dimention check

2


In [7]:
print(type(ass))

<class 'numpy.ndarray'>


In [8]:
arr=np.array(range(5))
print(arr)

[0 1 2 3 4]


In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
print(arr.ndim)

3


In [14]:
print(arr[1])

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr[0,1])

[4 5 6]


In [18]:
print(arr[0, 1, 2])


6


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)

print(arr[1:5])

[1 2 3 4 5 6 7]
[2 3 4 5]


In [21]:
print(arr[:5])

[1 2 3 4 5]


In [22]:
print(arr[3:])

[4 5 6 7]


In [23]:
print(arr[-5:-1])

[3 4 5 6]


In [24]:
print(arr[1:5:2])

[2 4]


In [25]:
print(arr[::2])

[1 3 5 7]


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [27]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [38]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [39]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [40]:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [41]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [42]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [46]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [47]:
import numpy as np

arr = np.array([9,5,4,8,3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3 4 5 8 9]


In [48]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [49]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]
